### ISSUE TITLE
Impossible to invoke the plugin functions.

### ISSUE THREAD

**Issue by Erquint** [kanutron/AssistantAI#1]
I tried installing the package in the latest Sublime Text 3 (3.2.2 Build 3211) and configuring the Codestral servers as such:
<details>
<summary>Click to reveal condensed settings JSON codeblock.</summary>

```json
{
  "servers": [
    {
      "id": "codestral-gratis-main",
      "name": "Codestral Gratis Main",
      "description": "Using the gratis codestral.mistral.ai hostname, requiring an API key provided in exchange for user's phone number and personal data. Using the main codestral-latest model as opposed to codestral-mamba-latest model.",
      "url": "https://codestral.mistral.ai",
      "timeout": 60,
      "required_credentials": ["api_key"],
      "headers": {
        "Authorization": "Bearer ${api_key}",
        "Content-Type": "application/json",
        "cache-control": "no-cache",
      },
      "endpoints": {
        "completions": {
          "name": "Completions",
          "icon": "᠁",
          "method": "POST",
          "resource": "/v1/fim/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "prompt": "string",
            "suffix": "string",
            "max_tokens": "integer",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "logprobs": "integer",
            "echo": "boolean",
            "stop": "string",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "best_of": "integer",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-latest",
            "prompt": "${text}",
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/text",
            }
          }
        },
        "chat_completions": {
          "name": "Chat Completions",
          "icon": "⇆",
          "method": "POST",
          "resource": "/v1/chat/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "messages": "string",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "stop": "string",
            "max_tokens": "integer",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-latest",
            "messages": [
              {
                "role": "user",
                "content": "${text}",
              }
            ]
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/message/content",
            }
          }
        }
      }
    },
    {
      "id": "codestral-gratis-mamba",
      "name": "Codestral Gratis Mamba",
      "description": "Using the gratis codestral.mistral.ai hostname, requiring an API key provided in exchange for user's phone number and personal data. Using the codestral-mamba-latest model as opposed to main codestral-latest model.",
      "url": "https://codestral.mistral.ai",
      "timeout": 60,
      "required_credentials": ["api_key"],
      "headers": {
        "Authorization": "Bearer ${api_key}",
        "Content-Type": "application/json",
        "cache-control": "no-cache",
      },
      "endpoints": {
        "completions": {
          "name": "Completions",
          "icon": "᠁",
          "method": "POST",
          "resource": "/v1/fim/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "prompt": "string",
            "suffix": "string",
            "max_tokens": "integer",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "logprobs": "integer",
            "echo": "boolean",
            "stop": "string",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "best_of": "integer",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-mamba-latest",
            "prompt": "${text}",
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/text",
            }
          }
        },
        "chat_completions": {
          "name": "Chat Completions",
          "icon": "⇆",
          "method": "POST",
          "resource": "/v1/chat/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "messages": "string",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "stop": "string",
            "max_tokens": "integer",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-mamba-latest",
            "messages": [
              {
                "role": "user",
                "content": "${text}",
              }
            ]
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/message/content",
            }
          }
        }
      }
    },
    {
      "id": "le-platforme-codestral-main",
      "name": "Le Platforme Codestral Main",
      "description": "Using the gratis api.mistral.ai hostname, requiring an API key provided under Le Platforme subscription plan, which is currently provided either for a fee or in exchange for permission to process sent data for Le Platforme development. Using the main codestral-latest model as opposed to codestral-mamba-latest model.",
      "url": "https://api.mistral.ai",
      "timeout": 60,
      "required_credentials": ["api_key"],
      "headers": {
        "Authorization": "Bearer ${api_key}",
        "Content-Type": "application/json",
        "cache-control": "no-cache",
      },
      "endpoints": {
        "completions": {
          "name": "Completions",
          "icon": "᠁",
          "method": "POST",
          "resource": "/v1/fim/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "prompt": "string",
            "suffix": "string",
            "max_tokens": "integer",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "logprobs": "integer",
            "echo": "boolean",
            "stop": "string",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "best_of": "integer",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-latest",
            "prompt": "${text}",
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/text",
            }
          }
        },
        "chat_completions": {
          "name": "Chat Completions",
          "icon": "⇆",
          "method": "POST",
          "resource": "/v1/chat/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "messages": "string",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "stop": "string",
            "max_tokens": "integer",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-latest",
            "messages": [
              {
                "role": "user",
                "content": "${text}",
              }
            ]
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/message/content",
            }
          }
        }
      }
    },
    {
      "id": "le-platforme-codestral-mamba",
      "name": "Le Platforme Codestral Mamba",
      "description": "Using the gratis api.mistral.ai hostname, requiring an API key provided under Le Platforme subscription plan, which is currently provided either for a fee or in exchange for permission to process sent data for Le Platforme development. Using the codestral-mamba-latest model as opposed to main codestral-latest model.",
      "url": "https://api.mistral.ai",
      "timeout": 60,
      "required_credentials": ["api_key"],
      "headers": {
        "Authorization": "Bearer ${api_key}",
        "Content-Type": "application/json",
        "cache-control": "no-cache",
      },
      "endpoints": {
        "completions": {
          "name": "Completions",
          "icon": "᠁",
          "method": "POST",
          "resource": "/v1/fim/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "prompt": "string",
            "suffix": "string",
            "max_tokens": "integer",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "logprobs": "integer",
            "echo": "boolean",
            "stop": "string",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "best_of": "integer",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-mamba-latest",
            "prompt": "${text}",
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/text",
            }
          }
        },
        "chat_completions": {
          "name": "Chat Completions",
          "icon": "⇆",
          "method": "POST",
          "resource": "/v1/chat/completions",
          "required_vars": ["text"],
          "valid_params": {
            "model": "string",
            "messages": "string",
            "temperature": "number",
            "top_p": "number",
            "n": "integer",
            "stream": "boolean",
            "stop": "string",
            "max_tokens": "integer",
            "presence_penalty": "number",
            "frequency_penalty": "number",
            "logit_bias": "object",
            "user": "string",
          },
          "request": {
            "model": "codestral-mamba-latest",
            "messages": [
              {
                "role": "user",
                "content": "${text}",
              }
            ]
          },
          "response": {
            "output": "${text}",
            "paths": {
              "error": "error",
              "text": "choices/0/message/content",
            }
          }
        }
      }
    }
  ],
  "credentials": {
    "codestral-gratis-main": {
      "api_key": "REDACTED"
    },
    "codestral-gratis-mamba": {
      "api_key": "REDACTED"
    },
    "le-platforme-codestral-main": {
      "api_key": "REDACTED"
    },
    "le-platforme-codestral-mamba": {
      "api_key": "REDACTED"
    }
  }
}
```

</details>

Following the usage instructions in the README, I enter `AssistantAI` in the command palette and nothing comes up. I venture into `Preferences → Package Settings → AssistantAI → Key Bindings` and it opens `%AppData%\Sublime Text 3\Packages\User\Default (Windows).sublime-keymap`.  

This presents no way to invoke AssistantAI plugin's funtionality.

**Comment by Erquint** [comment]
Have you made a mistake in publishing the package..?
![image](https://github.com/user-attachments/assets/43fef8fa-a2e5-4977-b892-6b5c3a8b0455)

**Comment by kanutron** [comment]
Hi @Erquint 

The quickest way to see if the plugin is well-installed is to invoke **Command Palette**:
- Tools > Command Palette (or Cmd+Shift+P).

Then search for `AssistantAI` command and hit enter.

You should see your prompts.

- If "AssistantAI" command don't show up, then the plugin is not installed, or it encountered some error.
- If "AssistantAI" command show, but once invoked, no prompts list appears, then is miss configured.

Pay attention to status bar outputs.

>Note; the prompts list is sensitive to the selected text when invoking the command, so I recommend invoking the AssistantAI command with some text selected.

For your reference, my Key Bindings files looks like this 

```json
[
    {
        "keys": ["alt+shift+p"],
        "command": "assistant_ai_prompt",
    },
    {
        // dumps current processed settings in a new buffer
        // useful when debugging new servers and prompts specifications
        "keys": ["alt+shift+d"],
        "command": "assistant_ai_dump",
    }
]
```

I don't see any prompt configured in your settings. Make sure you have some prompt that requires the specified endpoints.

Have to say that back when I coded this plugin, there was no Copilot, Cursor and similar solutions. Now, I'm not using it and, looks a bit outdated. Perhaps I should deprecate it. Although the proposal is quite flexible although complex to set up, seems that you could achieve what you intend to do.

And about ST3 vs ST4; they both are compatible so should work in both ST3 and ST4.

**Comment by Erquint** [comment]
> The quickest way to see if the plugin is well-installed is to invoke **Command Palette**:
> 
> * Tools > Command Palette (or Cmd+Shift+P).
> 
> Then search for `AssistantAI` command and hit enter.

That's what I described already having done in the head post to no avail.

> * If "AssistantAI" command don't show up, then the plugin is not installed, or it encountered some error.
> * If "AssistantAI" command show, but once invoked, no prompts list appears, then is miss configured.

You are incorrect there. It's neither of those options. The command is not present in the palette but the plugin is installed. I checked that by upgrading ST installation to major version 4 in a filesystem overlay sandbox without having to reinstall the plugin — it just started working on the latest version of Sublime Text 4. Still won't on the latest version of Sublime Text 3.

> I don't see any prompt configured in your settings. Make sure you have some prompt that requires the specified endpoints.

You are correct that I did not configure prompts. I was not sure I'm intended to do so, wrongly assuming that I could reuse prompts generally defined in the plugin. Guess I could copy and adapt them…  

The overall structure of configuration is still largely a mystery to me.  
I'd expect that the root config would point to the OpenAI and Gitea config files to for the plugin to load and then those would define the servers and such. Instead I guess you hardcoded those two and expect people to suggest others in GH issues. And those files in turn have both `servers`, `prompts`, `default_servers` and `default_prompts`, which also confuses me. You're free to use the snippet I included in the head post for Codestral. But I think it would make more sense to redesign the config architecture.

> Have to say that back when I coded this plugin, there was no Copilot, Cursor and similar solutions. Now, I'm not using it and, looks a bit outdated. Perhaps I should deprecate it. Although the proposal is quite flexible although complex to set up, seems that you could achieve what you intend to do.

GitHub Copilot was initially released in 2021. Codota launched in 2013, acquired Tabnine in 2019 and rebranded itself as Tabnine in 2021, murderizing its competitor — Kite (RIP 2014-2021). TabNine officially dropped support for ST, but their ST3 plugin released in 2018 still works great. Cursor was [announced](<https://x.com/amanrsanger/status/1615539968772050946>) in January of 2023, in February of the same year you made your [initial commit](<https://github.com/kanutron/AssistantAI/commit/250259e81616afbba73bcdd5d801d61f83f2149f>) and in March Cursor [released](<https://web.archive.org/web/20230316121339/https://www.cursor.so/>) the first public build.

But despite all of that, I think there is a niche for the way your plugin is doing things. I was ready to explore this approach when installing it.

> And about ST3 vs ST4; they both are compatible so should work in both ST3 and ST4.

Not in my experience as I described above. Have you tested it in ST3 recently? Is it only broken for me somehow?

**Comment by kanutron** [comment]
Hi @Erquint 

>Not in my experience as I described above. Have you tested it in ST3 recently? Is it only broken for me somehow?

You are right.

Seems I did the wrong assumption that Python 3.8 is also supported by Sublime Text 3. I just tested it in a fresh installation of ST3, and indeed doesn't work. You can see the problem if you open the ST console (`View > Show Console`). AssistantAI raises several "Invalid Syntax" exceptions. :-(

Here is the problem:
- AssistantAI needs python 3.8, and as such, the file `.python-version` in the plugin root states that.
- Sublime Text 3 and 4 are compatible, but now I learned that ST3 only supports plugins written for Python 3.3, and specifying that requires 3.8 have no effect (unlike in ST4). 

To make it fully compatible I should change the code, avoiding usage of format strings (python 3.6+ feature) and type hints.

> Have you made a mistake in publishing the package..?

Now it's clear to me that yes. 

I should change it to ST4, or, make the plugin to run in Python 3.3.

I'll spend some time now to try to make it work with Python3.3, and if it works, I'll release an update. Otherwise, change to ST4 in Package Control.

> The overall structure of configuration is still largely a mystery to me.

That is an indicator that documentation improvements are needed.

**Comment by kanutron** [comment]
BTW; I'm wondering why you're restricted to ST3. Is that a common reason for people using ST3 instead of ST4?

**Comment by kanutron** [comment]
Hi @Erquint 

With the latest release [1.2.0](https://github.com/kanutron/AssistantAI/releases/tag/1.2.0), and as soon as it is published in [Package Control](https://packagecontrol.io/packages/AssistantAI), you should be able to use it in ST3.

It works for me in both, ST3 and ST4, fresh installs (only tested in macOS though).

Let me know if it works now.

**Comment by Erquint** [comment]
It's just a case of "if it ain't broke — don't fix it" and major SemVer versions are breaking. SemVer schema can be read as:
```pwsh
# Normative definition.
Major.Minor.Patch
# Alternative definition I prefer.
BREAKING.Feature.Fix
```
I keep intending to try backing my installation up in case I need to downgrade later, upgrading and seeing if I can salvage it, but haven't found time and headroom, especially when ST3 serves my needs perfectly and perhaps some plugins I use are unmaintained and their packages were not updated to reflect support for ST4. When you say they're compatible — maybe you mean that ST4 will just work with ST3 plugins even without the tag…

Reading your response, I was wondering if there's a way to hack new Python into ST3, but I guess that's not necessary anymore. I'll check out the plugin soon-ish, hopefully. Thank you for backporting! Even if I upgrade ST, it would probably benefit other holdouts.

## P. S.

Looking back at the settings JSONs I included in the head post, I remember identifying several problems with it as I came across it again now and then in my files, but don't currently remember what those were.

**Comment by Erquint** [comment]
Okay, I just tested again in ST3 to confirm basic functionality. I do apologize for the delay.  
It does seem to load correctly now and show up in UI.  
It is able to query inference and input returned text at least for some of the configs.  
Beyond that, it still does seem too obscurely implemented for me to test extensively.  
But this test does in fact confirm this issue as resolved. Thank you again.
